# -*- coding: utf-8 -*-
"""Control_sim.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A-agbpMzn4Z4-ZZvsXXEZATSc51oibM-
"""

import numpy as np
import matplotlib.pyplot as plt
import control as ctrl

# 1. Motor Parameters & State-Space Definition
J, b, Kt, Ke, R, L = 0.01, 0.1, 0.01, 0.01, 1.0, 0.5

A = np.array([[-b/J, Kt/J], [-Ke/L, -R/L]])
B = np.array([[0], [1/L]])
C = np.array([[1, 0]])  # Output is speed
D = np.array([[0]])

sys_open = ctrl.ss(A, B, C, D)

# 2. Controller Design: Pole Placement
desired_poles = [-2, -3]
K_pp = ctrl.place(A, B, desired_poles)
sys_cl_pp = ctrl.ss(A - B @ K_pp, B, C, D)

# 3. Controller Design: LQR (Optimal Control)
Q = np.array([[10, 0], [0, 1]])
R_lqr = np.array([[1]])
K_lqr, _, _ = ctrl.lqr(A, B, Q, R_lqr)
sys_cl_lqr = ctrl.ss(A - B @ K_lqr, B, C, D)

# 4. Simulation & Performance Analysis
t = np.linspace(0, 5, 1000)
t1, y1 = ctrl.step_response(sys_open, T=t)
t2, y2 = ctrl.step_response(sys_cl_pp, T=t)
t3, y3 = ctrl.step_response(sys_cl_lqr, T=t)

# 5. Visualization
plt.figure(figsize=(6, 4))
plt.plot(t1, y1, label="Open Loop", linestyle="--")
plt.plot(t2, y2, label="Pole Placement (State Feedback)")
plt.plot(t3, y3, label="LQR (Optimal Control)", linewidth=2)

plt.title("Motor Speed Control: Controller Comparison")
plt.xlabel("Time (s)")
plt.ylabel("Angular Speed")
plt.legend()
plt.grid(True)
plt.show()

# 6. Print Performance Metrics
print("--- Performance Metrics ---")
for name, sys in [("Open Loop", sys_open), ("Pole Placement", sys_cl_pp), ("LQR", sys_cl_lqr)]:
    info = ctrl.step_info(sys)
    print(f"\n{name}:")
    print(f"  Rise Time: {info['RiseTime']:.4f}s")
    print(f"  Settling Time: {info['SettlingTime']:.4f}s")
    print(f"  Overshoot: {info['Overshoot']:.2f}%")

"""Project: State-Space Control System Design and Simulation

Modeled a dynamic system using state-space representation in Python

Designed state-feedback controllers using Pole Placement and LQR optimal control

Simulated open-loop and closed-loop system responses and evaluated performance metrics such as rise time and settling time
"""